service: twofac
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 3

  apiGateway:
    apiKeys:
      - exchangeTextKey
    usagePlan:
      throttle:
        burstLimit: 3
        rateLimit: 3

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: !GetAtt CodeTable.Arn
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: '*'

  environment:
    CODETABLE: !Ref CodeTable

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  SendSMS:
    handler: bin/sendsms
    events:
      - http:
          path: /sms/{number}
          method: post
          private: true
  Verify:
    handler: bin/verify
    events:
      - http:
          path: /verify/{number}/{code}
          method: post
          private: true

resources:
  Resources:
    CodeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-codes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true